adb root
adb remount
adb shell setprop vendor.debug.vratsfcore.enable 1
adb shell setprop vendor.debug.tsfcore.crm 1
adb shell setprop vendor.debug.tsfcore.orb1 1
adb shell setprop vendor.debug.tsfcore.alv 1
adb shell setprop vendor.debug.tsfcore.dfs 1
adb shell setprop vendor.debug.tsfcore.dbl2 1
adb shell setprop vendor.debug.tsfcore.orc2 1
adb shell setprop vendor.debug.tsfcore.dsl1 1
adb shell setprop vendor.debug.gutsfcore.enable 1
adb shell setprop vendor.debug.tsfcore.cbi 1
adb shell setprop vendor.debug.tsfcore.cbm 1
adb shell setprop vendor.debug.tsfcore.orb2 1
adb shell setprop vendor.debug.tsfcore.db2 1
adb shell setprop vendor.debug.tsfcore.pri 1
adb shell setprop vendor.debug.tsfcore.ds1 1
adb shell setprop vendor.debug.tsfcore.vec 1
adb shell setprop vendor.debug.tsfcore.owd 1
adb shell setprop vendor.debug.tsfcore.dh1 1
adb shell setprop vendor.debug.tsfcore.dsl2 1
adb shell setprop vendor.debug.bdtsfcore.enable 1
adb shell setprop vendor.debug.tsfcore.dbl1 1
adb shell setprop vendor.debug.tsfcore.opc 1
adb shell setprop vendor.debug.tsfcore.ds2 1
adb shell setprop vendor.debug.tsfcore.ht 1
adb shell setprop vendor.debug.tsfcore.orl2 1
adb shell setprop vendor.debug.tsfcore.dls 1
adb shell setprop vendor.debug.tsfcore.cbl 1
adb shell setprop vendor.debug.tsfcore.ords 1
adb shell setprop vendor.debug.tsfcore.dlu 1
adb shell setprop vendor.debug.tsfcore.fpc 1
adb shell setprop vendor.debug.tsfcore.cru 1
adb shell setprop vendor.debug.tsfcore.tcr 1
adb shell setprop vendor.debug.tsfcore.ory 1
adb shell setprop vendor.debug.tsfcore_exifdbg.enable 1
adb shell setprop vendor.debug.tsfcore.dfu 1
adb shell setprop vendor.debug.tsfcore.crl 1
adb shell setprop vendor.debug.cns.enable 1
adb shell setprop vendor.debug.tsfcore.cri 1
adb shell setprop vendor.debug.tsfcore.orl1 1
adb shell setprop endor.debug.tsfcore.dh2 1
adb shell setprop vendor.debug.tsfcore.cbd 1
adb shell setprop vendor.debug.tsfcore.orc1 1
adb shell setprop vendor.debug.tsfcore.orb0 1
adb shell setprop vendor.debug.tsfcore.orb3 1
adb shell setprop vendor.debug.tsfcore.enable 1
adb shell setprop vendor.debug.tsfcore.filedump.enable 1
adb shell setprop vendor.debug.tsfcore.tcb 1
adb shell setprop vendor.debug.tsfcore.lt 1
adb shell setprop vendor.debug.tsfcore.crd 1
adb shell setprop vendor.debug.tsfcore.dsc 1
adb shell setprop vendor.debug.tsfcore.dcu 1
adb shell setprop vendor.debug.tsfcore.db1 1
adb shell setprop vendor.debug.tsfcore.cbu 1
adb shell pkill camera*